config/routes.rb
Invasion::Application.routes.draw do
 get "account" => "users#show", :as => "account"
 get "logout" => "sessions#destroy", :as => "logout"
 get "login" => "sessions#new", :as => "login"
 get "signup" => "users#new", :as => "signup"
 get "dashboard" => "home#dashboard", :as => "dashboard"
 resources :users
 resources :sessions
 root :to => "home#index" 
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :user_name, :email, :password, :password_confirmation
  
  before_save :encrypt_password  
  validates_confirmation_of :password
  
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_uniqueness_of :email
  
  validates_presence_of :user_name
  validates_uniqueness_of :user_name
  
  def self.authenticate(email, pass)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(pass, user.password_salt)
      user
    else
      nil
    end    
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user  
  helper_method :authenticate
  
  private  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue
    @current_user = nil
  end

  def authenticate
    redirect_to login_url unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate, :only => :dashboard
  
  def dashboard    
    respond_to do |format|
      format.html { render 'dashboard' }
      format.xml  { }
    end
  end

  def index
    respond_to do |format|
      format.html { render 'index' }
      format.xml  { }
    end    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :authenticate, :only => :destroy

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    
    if user
      session[:user_id] = user.id
      redirect_to dashboard_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
  
  def destroy    
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :except => [:new, :create]
  
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create    
    @user = User.new(params[:user])

    if invalid_code = (params[:signup_code] != ENV['signup_code'])
      @user.errors.add :base, t('errors.invalid_signup_code')
    end
      
    respond_to do |format|
      if !invalid_code && @user.save
        format.html { redirect_to login_url, :notice => 'User was successfully created.' }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])    
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_dash_message.en.html.erb
<p>Feel free to poke the <%= link_to "User Manager", users_path %> with a stick until you feel like you want to <%= link_to "Log Out", logout_path %>.</p>

app/views/home/dashboard.html.erb
<h2><%= t 'misc.dashboard' %></h2>
<%= render :partial => 'dash_message' %>

app/views/home/index.en.html.erb
<p>
<% if current_user %>
  Hey there <%= current_user.user_name %>.  Wanna check out the <%= link_to t('navigation.dashboard'), dashboard_path %>? If not, all that's really left to do is <%= link_to t('navigation.logout'), logout_path %>!
<% else %>
  Hello friend!  You look like an adventurous soul, would you like to <%= link_to "Log in", login_path %> or <%= link_to "Sign Up", signup_path %>?
<% end %>
</p>

app/views/layouts/_app_header.en.html.erb
<% if current_user %>
  <div class="session_panel"><p>Poking around as <%= current_user.user_name %>.  <%= link_to t('navigation.logout'), logout_path %>?</p></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t 'misc.site_title' %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= render :partial => 'layouts/app_header' %>
<%= yield  %>
</body>
</html>

app/views/users/edit.html.erb
<h1><%= t 'navigation.editing_items', :items => User.human_name %></h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2> <%= t :x_error_messages, :count => @user.errors.count %></h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>  
  <% yield f %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to t('navigation.show'), @user %> |
<%= link_to t('navigation.back'), :back %>

app/views/users/index.html.erb
<h1><%= t 'navigation.listing_items', :items => pluralize(@users.count, User.human_name) %></h1>

<table>
  <tr>
    <th><%= User.human_attribute_name 'id' %></th>
    <th><%= User.human_attribute_name 'user_name' %></th>
    <th><%= User.human_attribute_name 'email' %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.user_name %></td>
    <td><%= user.email %></td>
    <td><%= link_to t('navigation.show'), user %></td>
    <td><%= link_to t('navigation.edit'), edit_user_path(user) %></td>
    <td><%= link_to t('navigation.destroy'), user, :confirm => t('confirm'), :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<p><%= link_to t('navigation.new_item', :item => User.human_name), new_user_path %> |
   <%= link_to t('misc.dashboard'), dashboard_path %></p>

app/views/users/new.html.erb
<h1><%= t 'navigation.signup' %></h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2> <%= t :x_error_messages, :count => @user.errors.count %></h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>  
  <div class="field">
    <%= label_tag :signup_code, t('misc.signup_code') %><br />
    <%= text_field_tag :signup_code %><br />
  </div> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to t('navigation.back'), :back %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= User.human_attribute_name 'user_name' %>:</b>
  <%= @user.user_name %>
</p>

<p>
  <b><%= User.human_attribute_name 'email' %>:</b>
  <%= @user.email %>
</p>

<%= link_to t('navigation.edit'), edit_user_path(@user) %> |
<%= link_to t('navigation.back'), users_path %>